export type CardArtEntry = {
  fileName: string;
  textureKey: string;
};

export const CARD_ART_CATALOG: Record<string, CardArtEntry> = {
  arcane_bolt: { textureKey: 'card-art:arcane_bolt_spell', fileName: 'arcane-bolt-spell.png' },
  armor_break: { textureKey: 'card-art:armor_break_anime', fileName: 'armor-break-anime.png' },
  battle_howl: { textureKey: 'card-art:battle_howl_anime', fileName: 'battle-howl-anime.png' },
  concussive_shot: { textureKey: 'card-art:concussive_shot_anime', fileName: 'concussive-shot-anime.png' },
  crushing_blow: { textureKey: 'card-art:crushing_blow_anime', fileName: 'crushing-blow-anime.png' },
  crippling_strike: { textureKey: 'card-art:crippling_strike_anime', fileName: 'crippling-strike-anime.png' },
  fireball: { textureKey: 'card-art:fireball_anime', fileName: 'fireball-anime.png' },
  follow_through: { textureKey: 'card-art:follow_through_anime', fileName: 'follow-through-anime.png' },
  frost_ward: { textureKey: 'card-art:frost_ward_anime', fileName: 'frost-ward-anime.png' },
  hex_of_frailty: { textureKey: 'card-art:hex_of_frailty_anime', fileName: 'hex-of-frailty-anime.png' },
  hunter_shot: { textureKey: 'card-art:hunter_shot_anime', fileName: 'hunter-shot-anime.png' },
  hamstring: { textureKey: 'card-art:hamstring_anime', fileName: 'hamstring-anime.png' },
  iron_bulwark: { textureKey: 'card-art:iron_bulwark_anime', fileName: 'iron-bulwark-anime.png' },
  judgment_light: { textureKey: 'card-art:judgment_light_anime', fileName: 'judgment-light-anime.png' },
  leeching_fang: { textureKey: 'card-art:leeching_fang_anime', fileName: 'leeching-fang-anime.png' },
  // lucky-charm-anime.png exists on disk but the 'lucky_charm' skill was
  // removed 2026-07-23 — re-add the entry here if the card ever returns.
  mana_ward: { textureKey: 'card-art:mana_ward_anime', fileName: 'mana-ward-anime.png' },
  mending_light: { textureKey: 'card-art:mending_light_anime', fileName: 'mending-light-anime.png' },
  prism_barrier: { textureKey: 'card-art:prism_barrier_anime', fileName: 'prism-barrier-anime.png' },
  purging_strike: { textureKey: 'card-art:purging_strike_anime', fileName: 'purging-strike-anime.png' },
  purify: { textureKey: 'card-art:purify_anime', fileName: 'purify-anime.png' },
  rending_claws: { textureKey: 'card-art:rending_claws_anime', fileName: 'rending-claws-anime.png' },
  rupturing_strike: { textureKey: 'card-art:rupturing_strike_anime', fileName: 'rupturing-strike-anime.png' },
  savage_bite: { textureKey: 'card-art:savage_bite_anime', fileName: 'savage-bite-anime.png' },
  second_wind: { textureKey: 'card-art:second_wind_anime', fileName: 'second-wind-anime.png' },
  shield_splitter: { textureKey: 'card-art:shield_splitter_anime', fileName: 'shield-splitter-anime.png' },
  shadow_bolt: { textureKey: 'card-art:shadow_bolt_anime', fileName: 'shadow-bolt-anime.png' },
  slow_hex: { textureKey: 'card-art:slow_hex_anime', fileName: 'slow-hex-anime.png' },
  soul_rend: { textureKey: 'card-art:soul_rend_anime', fileName: 'soul-rend-anime.png' },
  stunning_smash: { textureKey: 'card-art:stunning_smash_anime', fileName: 'stunning-smash-anime.png' },
  sword_slash: { textureKey: 'card-art:sword_slash_anime', fileName: 'sword-slash-anime.png' },
  time_crystal: { textureKey: 'card-art:time_crystal_anime', fileName: 'time-crystal-anime.png' },
  venom_fang: { textureKey: 'card-art:venom_fang_anime', fileName: 'venom-fang-anime.png' },
  ward_of_silence: { textureKey: 'card-art:ward_of_silence_anime', fileName: 'ward-of-silence-anime.png' },
  war_banner: { textureKey: 'card-art:war_banner_anime', fileName: 'war-banner-anime.png' },
  ruinous_hex: { textureKey: 'card-art:ruinous_hex_anime', fileName: 'ruinous-hex-anime.png' },
  twin_slash: { textureKey: 'card-art:twin_slash_anime', fileName: 'twin-slash-anime.png' },
  ember_lash: { textureKey: 'card-art:ember_lash_anime', fileName: 'ember-lash-anime.png' },
  cinder_dart: { textureKey: 'card-art:cinder_dart_anime', fileName: 'cinder-dart-anime.png' },
  scorching_brand: { textureKey: 'card-art:scorching_brand_anime', fileName: 'scorching-brand-anime.png' },
  wildfire_surge: { textureKey: 'card-art:wildfire_surge_anime', fileName: 'wildfire-surge-anime.png' },
  inferno_eruption: { textureKey: 'card-art:inferno_eruption_anime', fileName: 'inferno-eruption-anime.png' },
  static_jolt: { textureKey: 'card-art:static_jolt_anime', fileName: 'static-jolt-anime.png' },
  thunder_step: { textureKey: 'card-art:thunder_step_anime', fileName: 'thunder-step-anime.png' },
  chain_spark: { textureKey: 'card-art:chain_spark_anime', fileName: 'chain-spark-anime.png' },
  overcharge: { textureKey: 'card-art:overcharge_anime', fileName: 'overcharge-anime.png' },
  storm_surge: { textureKey: 'card-art:storm_surge_anime', fileName: 'storm-surge-anime.png' },
  thorn_bite: { textureKey: 'card-art:thorn_bite_anime', fileName: 'thorn-bite-anime.png' },
  verdant_touch: { textureKey: 'card-art:verdant_touch_anime', fileName: 'verdant-touch-anime.png' },
  blooming_vine: { textureKey: 'card-art:blooming_vine_anime', fileName: 'blooming-vine-anime.png' },
  overgrowth: { textureKey: 'card-art:overgrowth_anime', fileName: 'overgrowth-anime.png' },
  glacial_spike: { textureKey: 'card-art:glacial_spike_anime', fileName: 'glacial-spike-anime.png' },
  frost_shackle: { textureKey: 'card-art:frost_shackle_anime', fileName: 'frost-shackle-anime.png' },
  deep_freeze: { textureKey: 'card-art:deep_freeze_anime', fileName: 'deep-freeze-anime.png' },
  lance_thrust: { textureKey: 'card-art:lance_thrust_anime', fileName: 'lance-thrust-anime.png' },
  braced_pike: { textureKey: 'card-art:braced_pike_anime', fileName: 'braced-pike-anime.png' },
  piercing_reach: { textureKey: 'card-art:piercing_reach_anime', fileName: 'piercing-reach-anime.png' },
  impaling_charge: { textureKey: 'card-art:impaling_charge_anime', fileName: 'impaling-charge-anime.png' },
  rapid_volley: { textureKey: 'card-art:rapid_volley_anime', fileName: 'rapid-volley-anime.png' },
  piercing_arrow: { textureKey: 'card-art:piercing_arrow_anime', fileName: 'piercing-arrow-anime.png' },
  marksman_shot: { textureKey: 'card-art:marksman_shot_anime', fileName: 'marksman-shot-anime.png' },
  barrage: { textureKey: 'card-art:barrage_anime', fileName: 'barrage-anime.png' },
  bastion_stance: { textureKey: 'card-art:bastion_stance_anime', fileName: 'bastion-stance-anime.png' },
  aegis_wall: { textureKey: 'card-art:aegis_wall_anime', fileName: 'aegis-wall-anime.png' },
  sanctified_bulwark: { textureKey: 'card-art:sanctified_bulwark_anime', fileName: 'sanctified-bulwark-anime.png' },
  fortress_bastion: { textureKey: 'card-art:fortress_bastion_anime', fileName: 'fortress-bastion-anime.png' },
  mending_aura: { textureKey: 'card-art:mending_aura_anime', fileName: 'mending-aura-anime.png' },
  swift_march: { textureKey: 'card-art:swift_march_anime', fileName: 'swift-march-anime.png' },
  warlord_banner: { textureKey: 'card-art:warlord_banner_anime', fileName: 'warlord-banner-anime.png' },
  renewing_wave: { textureKey: 'card-art:renewing_wave_anime', fileName: 'renewing-wave-anime.png' },
  vital_surge: { textureKey: 'card-art:vital_surge_anime', fileName: 'vital-surge-anime.png' },
  void_pierce: { textureKey: 'card-art:void_pierce_anime', fileName: 'void-pierce-anime.png' },
  annihilation_strike: { textureKey: 'card-art:annihilation_strike_anime', fileName: 'annihilation-strike-anime.png' },
};
