/**
 * Card art catalogue — skill id -> the ONE texture key and the ONE file the
 * game loads for it. Nothing else in the codebase names a card-art path.
 *
 * The files are `.webp` DERIVATIVES, produced by `scripts/encode-card-art.ts`
 * (`npm run art:encode`) from the `.png` masters in **`art-src/cards/`**:
 * max 1024 tall, WebP q82, ~95 KB each against the masters' ~2.3 MB. The
 * masters live OUTSIDE `public/` because `vite build` copies `public/`
 * verbatim — while they sat beside their derivatives every deploy shipped
 * 179 MB of PNG nothing fetches. The `.webp` here is generated but IS
 * committed (encoding needs Chromium, which the build does not have). See
 * that script's header for why 1024 (2.4x the tallest real draw) and why the
 * masters are never modified.
 *
 * Art is NOT loaded at boot. `cardArtLoader.ts` streams each texture in on
 * first use and the card renderers show `cardArtPlaceholder.ts` until it
 * lands — so a card with no catalogue entry at all (94 of 166 skills today)
 * and a card whose art is still in flight take the exact same code path.
 */
export type CardArtEntry = {
  fileName: string;
  textureKey: string;
};

/** Directory the catalogue's `fileName`s live in, served from `public/`. */
export const CARD_ART_BASE_PATH = '/game-art/cards';

/** The URL the loader fetches for one catalogue entry. */
export function cardArtUrl(entry: CardArtEntry): string {
  return `${CARD_ART_BASE_PATH}/${entry.fileName}`;
}

export const CARD_ART_CATALOG: Record<string, CardArtEntry> = {
  aegis_of_the_unbroken: { textureKey: 'card-art:aegis_of_the_unbroken_anime', fileName: 'aegis-of-the-unbroken-anime.webp' },
  arcane_bolt: { textureKey: 'card-art:arcane_bolt_spell', fileName: 'arcane-bolt-spell.webp' },
  armor_break: { textureKey: 'card-art:armor_break_anime', fileName: 'armor-break-anime.webp' },
  battle_howl: { textureKey: 'card-art:battle_howl_anime', fileName: 'battle-howl-anime.webp' },
  bramble_ward: { textureKey: 'card-art:bramble_ward_anime', fileName: 'bramble-ward-anime.webp' },
  bramblewrath: { textureKey: 'card-art:bramblewrath_anime', fileName: 'bramblewrath-anime.webp' },
  concussive_shot: { textureKey: 'card-art:concussive_shot_anime', fileName: 'concussive-shot-anime.webp' },
  crushing_blow: { textureKey: 'card-art:crushing_blow_anime', fileName: 'crushing-blow-anime.webp' },
  crippling_strike: { textureKey: 'card-art:crippling_strike_anime', fileName: 'crippling-strike-anime.webp' },
  fireball: { textureKey: 'card-art:fireball_anime', fileName: 'fireball-anime.webp' },
  follow_through: { textureKey: 'card-art:follow_through_anime', fileName: 'follow-through-anime.webp' },
  frost_ward: { textureKey: 'card-art:frost_ward_anime', fileName: 'frost-ward-anime.webp' },
  hex_of_frailty: { textureKey: 'card-art:hex_of_frailty_anime', fileName: 'hex-of-frailty-anime.webp' },
  hemorrhage: { textureKey: 'card-art:hemorrhage_anime', fileName: 'hemorrhage-anime.webp' },
  hunter_shot: { textureKey: 'card-art:hunter_shot_anime', fileName: 'hunter-shot-anime.webp' },
  hamstring: { textureKey: 'card-art:hamstring_anime', fileName: 'hamstring-anime.webp' },
  iron_bulwark: { textureKey: 'card-art:iron_bulwark_anime', fileName: 'iron-bulwark-anime.webp' },
  iron_maiden: { textureKey: 'card-art:iron_maiden_anime', fileName: 'iron-maiden-anime.webp' },
  iron_riposte: { textureKey: 'card-art:iron_riposte_anime', fileName: 'iron-riposte-anime.webp' },
  judgment_light: { textureKey: 'card-art:judgment_light_anime', fileName: 'judgment-light-anime.webp' },
  leeching_fang: { textureKey: 'card-art:leeching_fang_anime', fileName: 'leeching-fang-anime.webp' },
  // NOTE: the 'lucky_charm' skill was removed 2026-07-23 and its art
  // (lucky-charm-anime.png/.webp) was deleted with the 2026-08-30 art-src
  // move — recover it from git history if the card ever returns.
  mana_ward: { textureKey: 'card-art:mana_ward_anime', fileName: 'mana-ward-anime.webp' },
  mending_light: { textureKey: 'card-art:mending_light_anime', fileName: 'mending-light-anime.webp' },
  prism_barrier: { textureKey: 'card-art:prism_barrier_anime', fileName: 'prism-barrier-anime.webp' },
  purging_strike: { textureKey: 'card-art:purging_strike_anime', fileName: 'purging-strike-anime.webp' },
  purify: { textureKey: 'card-art:purify_anime', fileName: 'purify-anime.webp' },
  rending_claws: { textureKey: 'card-art:rending_claws_anime', fileName: 'rending-claws-anime.webp' },
  rupturing_strike: { textureKey: 'card-art:rupturing_strike_anime', fileName: 'rupturing-strike-anime.webp' },
  savage_bite: { textureKey: 'card-art:savage_bite_anime', fileName: 'savage-bite-anime.webp' },
  second_wind: { textureKey: 'card-art:second_wind_anime', fileName: 'second-wind-anime.webp' },
  shield_splitter: { textureKey: 'card-art:shield_splitter_anime', fileName: 'shield-splitter-anime.webp' },
  shadow_bolt: { textureKey: 'card-art:shadow_bolt_anime', fileName: 'shadow-bolt-anime.webp' },
  slow_hex: { textureKey: 'card-art:slow_hex_anime', fileName: 'slow-hex-anime.webp' },
  soul_rend: { textureKey: 'card-art:soul_rend_anime', fileName: 'soul-rend-anime.webp' },
  stunning_smash: { textureKey: 'card-art:stunning_smash_anime', fileName: 'stunning-smash-anime.webp' },
  sword_slash: { textureKey: 'card-art:sword_slash_anime', fileName: 'sword-slash-anime.webp' },
  time_crystal: { textureKey: 'card-art:time_crystal_anime', fileName: 'time-crystal-anime.webp' },
  venom_fang: { textureKey: 'card-art:venom_fang_anime', fileName: 'venom-fang-anime.webp' },
  ward_of_silence: { textureKey: 'card-art:ward_of_silence_anime', fileName: 'ward-of-silence-anime.webp' },
  war_banner: { textureKey: 'card-art:war_banner_anime', fileName: 'war-banner-anime.webp' },
  ruinous_hex: { textureKey: 'card-art:ruinous_hex_anime', fileName: 'ruinous-hex-anime.webp' },
  twin_slash: { textureKey: 'card-art:twin_slash_anime', fileName: 'twin-slash-anime.webp' },
  ember_lash: { textureKey: 'card-art:ember_lash_anime', fileName: 'ember-lash-anime.webp' },
  cinder_dart: { textureKey: 'card-art:cinder_dart_anime', fileName: 'cinder-dart-anime.webp' },
  cinder_skin: { textureKey: 'card-art:cinder_skin_anime', fileName: 'cinder-skin-anime.webp' },
  scorching_brand: { textureKey: 'card-art:scorching_brand_anime', fileName: 'scorching-brand-anime.webp' },
  wildfire_surge: { textureKey: 'card-art:wildfire_surge_anime', fileName: 'wildfire-surge-anime.webp' },
  inferno_eruption: { textureKey: 'card-art:inferno_eruption_anime', fileName: 'inferno-eruption-anime.webp' },
  static_jolt: { textureKey: 'card-art:static_jolt_anime', fileName: 'static-jolt-anime.webp' },
  thunder_step: { textureKey: 'card-art:thunder_step_anime', fileName: 'thunder-step-anime.webp' },
  chain_spark: { textureKey: 'card-art:chain_spark_anime', fileName: 'chain-spark-anime.webp' },
  overcharge: { textureKey: 'card-art:overcharge_anime', fileName: 'overcharge-anime.webp' },
  storm_surge: { textureKey: 'card-art:storm_surge_anime', fileName: 'storm-surge-anime.webp' },
  thorn_bite: { textureKey: 'card-art:thorn_bite_anime', fileName: 'thorn-bite-anime.webp' },
  verdant_touch: { textureKey: 'card-art:verdant_touch_anime', fileName: 'verdant-touch-anime.webp' },
  blooming_vine: { textureKey: 'card-art:blooming_vine_anime', fileName: 'blooming-vine-anime.webp' },
  overgrowth: { textureKey: 'card-art:overgrowth_anime', fileName: 'overgrowth-anime.webp' },
  glacial_spike: { textureKey: 'card-art:glacial_spike_anime', fileName: 'glacial-spike-anime.webp' },
  gutting_cleave: { textureKey: 'card-art:gutting_cleave_anime', fileName: 'gutting-cleave-anime.webp' },
  frost_shackle: { textureKey: 'card-art:frost_shackle_anime', fileName: 'frost-shackle-anime.webp' },
  deep_freeze: { textureKey: 'card-art:deep_freeze_anime', fileName: 'deep-freeze-anime.webp' },
  lance_thrust: { textureKey: 'card-art:lance_thrust_anime', fileName: 'lance-thrust-anime.webp' },
  braced_pike: { textureKey: 'card-art:braced_pike_anime', fileName: 'braced-pike-anime.webp' },
  piercing_reach: { textureKey: 'card-art:piercing_reach_anime', fileName: 'piercing-reach-anime.webp' },
  impaling_charge: { textureKey: 'card-art:impaling_charge_anime', fileName: 'impaling-charge-anime.webp' },
  rapid_volley: { textureKey: 'card-art:rapid_volley_anime', fileName: 'rapid-volley-anime.webp' },
  piercing_arrow: { textureKey: 'card-art:piercing_arrow_anime', fileName: 'piercing-arrow-anime.webp' },
  marksman_shot: { textureKey: 'card-art:marksman_shot_anime', fileName: 'marksman-shot-anime.webp' },
  barrage: { textureKey: 'card-art:barrage_anime', fileName: 'barrage-anime.webp' },
  bastion_stance: { textureKey: 'card-art:bastion_stance_anime', fileName: 'bastion-stance-anime.webp' },
  aegis_wall: { textureKey: 'card-art:aegis_wall_anime', fileName: 'aegis-wall-anime.webp' },
  sanctified_bulwark: { textureKey: 'card-art:sanctified_bulwark_anime', fileName: 'sanctified-bulwark-anime.webp' },
  fortress_bastion: { textureKey: 'card-art:fortress_bastion_anime', fileName: 'fortress-bastion-anime.webp' },
  mending_aura: { textureKey: 'card-art:mending_aura_anime', fileName: 'mending-aura-anime.webp' },
  swift_march: { textureKey: 'card-art:swift_march_anime', fileName: 'swift-march-anime.webp' },
  warlord_banner: { textureKey: 'card-art:warlord_banner_anime', fileName: 'warlord-banner-anime.webp' },
  renewing_wave: { textureKey: 'card-art:renewing_wave_anime', fileName: 'renewing-wave-anime.webp' },
  vital_surge: { textureKey: 'card-art:vital_surge_anime', fileName: 'vital-surge-anime.webp' },
  void_pierce: { textureKey: 'card-art:void_pierce_anime', fileName: 'void-pierce-anime.webp' },
  annihilation_strike: { textureKey: 'card-art:annihilation_strike_anime', fileName: 'annihilation-strike-anime.webp' },
  nettle_lash: { textureKey: 'card-art:nettle_lash_anime', fileName: 'nettle-lash-anime.webp' },
  purge_the_rot: { textureKey: 'card-art:purge_the_rot_anime', fileName: 'purge-the-rot-anime.webp' },
  retaliation_stance: { textureKey: 'card-art:retaliation_stance_anime', fileName: 'retaliation-stance-anime.webp' },
  silencing_slash: { textureKey: 'card-art:silencing_slash_anime', fileName: 'silencing-slash-anime.webp' },
  siphon_life: { textureKey: 'card-art:siphon_life_anime', fileName: 'siphon-life-anime.webp' },
  spotters_mark: { textureKey: 'card-art:spotters_mark_anime', fileName: 'spotters-mark-anime.webp' },
  storm_guard: { textureKey: 'card-art:storm_guard_anime', fileName: 'storm-guard-anime.webp' },
  sundering_roar: { textureKey: 'card-art:sundering_roar_anime', fileName: 'sundering-roar-anime.webp' },
  verdant_rebuke: { textureKey: 'card-art:verdant_rebuke_anime', fileName: 'verdant-rebuke-anime.webp' },
  warding_prayer: { textureKey: 'card-art:warding_prayer_anime', fileName: 'warding-prayer-anime.webp' },
  sanctum_thorn: { textureKey: 'card-art:sanctum_thorn_anime', fileName: 'sanctum-thorn-anime.webp' },
  bramblemend: { textureKey: 'card-art:bramblemend_anime', fileName: 'bramblemend-anime.webp' },
  warded_reprisal: { textureKey: 'card-art:warded_reprisal_anime', fileName: 'warded-reprisal-anime.webp' },
  bulwark_thicket: { textureKey: 'card-art:bulwark_thicket_anime', fileName: 'bulwark-thicket-anime.webp' },
  unbreakable_stance: { textureKey: 'card-art:unbreakable_stance_anime', fileName: 'unbreakable-stance-anime.webp' },
  umbral_ward: { textureKey: 'card-art:umbral_ward_anime', fileName: 'umbral-ward-anime.webp' },
  thorn_shackle: { textureKey: 'card-art:thorn_shackle_anime', fileName: 'thorn-shackle-anime.webp' },
  mortal_wound: { textureKey: 'card-art:mortal_wound_anime', fileName: 'mortal-wound-anime.webp' },
  barbed_rampart: { textureKey: 'card-art:barbed_rampart_anime', fileName: 'barbed-rampart-anime.webp' },
  crippling_gore: { textureKey: 'card-art:crippling_gore_anime', fileName: 'crippling-gore-anime.webp' },
  poison_bloom: { textureKey: 'card-art:poison_bloom_anime', fileName: 'poison-bloom-anime.webp' },
  poison_ritual: { textureKey: 'card-art:poison_ritual_anime', fileName: 'poison-ritual-anime.webp' },
  evasive_cordon: { textureKey: 'card-art:evasive_cordon_anime', fileName: 'evasive-cordon-anime.webp' },
  shockwave_slam: { textureKey: 'card-art:shockwave_slam_anime', fileName: 'shockwave-slam-anime.webp' },
  arc_cascade: { textureKey: 'card-art:arc_cascade_anime', fileName: 'arc-cascade-anime.webp' },
  line_breaker: { textureKey: 'card-art:line_breaker_anime', fileName: 'line-breaker-anime.webp' },
  disarming_blow: { textureKey: 'card-art:disarming_blow_anime', fileName: 'disarming-blow-anime.webp' },
  mind_frost: { textureKey: 'card-art:mind_frost_anime', fileName: 'mind-frost-anime.webp' },
  toxic_bulwark: { textureKey: 'card-art:toxic_bulwark_anime', fileName: 'toxic-bulwark-anime.webp' },
  nettle_ward: { textureKey: 'card-art:nettle_ward_anime', fileName: 'nettle-ward-anime.webp' },
  blight_feast: { textureKey: 'card-art:blight_feast_anime', fileName: 'blight-feast-anime.webp' },
  second_bite: { textureKey: 'card-art:second_bite_anime', fileName: 'second-bite-anime.webp' },
  thorn_reckoning: { textureKey: 'card-art:thorn_reckoning_anime', fileName: 'thorn-reckoning-anime.webp' },
  bleed_executioner: { textureKey: 'card-art:bleed_executioner_anime', fileName: 'bleed-executioner-anime.webp' },
  burn_detonator: { textureKey: 'card-art:burn_detonator_anime', fileName: 'burn-detonator-anime.webp' },
  control_opportunist: { textureKey: 'card-art:control_opportunist_anime', fileName: 'control-opportunist-anime.webp' },
  debuff_crusher: { textureKey: 'card-art:debuff_crusher_anime', fileName: 'debuff-crusher-anime.webp' },
  aegis_charge: { textureKey: 'card-art:aegis_charge_anime', fileName: 'aegis-charge-anime.webp' },
  deadweight_toll: { textureKey: 'card-art:deadweight_toll_anime', fileName: 'deadweight-toll-anime.webp' },
  dulling_hex: { textureKey: 'card-art:dulling_hex_anime', fileName: 'dulling-hex-anime.webp' },
  sapping_arc: { textureKey: 'card-art:sapping_arc_anime', fileName: 'sapping-arc-anime.webp' },
  sanctuary_overflow: { textureKey: 'card-art:sanctuary_overflow_anime', fileName: 'sanctuary-overflow-anime.webp' },
  penitent_mending: { textureKey: 'card-art:penitent_mending_anime', fileName: 'penitent-mending-anime.webp' },
  vow_broken: { textureKey: 'card-art:vow_broken_anime', fileName: 'vow-broken-anime.webp' },
  cornered_beast: { textureKey: 'card-art:cornered_beast_anime', fileName: 'cornered-beast-anime.webp' },
  leaden_bite: { textureKey: 'card-art:leaden_bite_anime', fileName: 'leaden-bite-anime.webp' },
  finishing_cleave: { textureKey: 'card-art:finishing_cleave_anime', fileName: 'finishing-cleave-anime.webp' },
  thermal_shock: { textureKey: 'card-art:thermal_shock_anime', fileName: 'thermal-shock-anime.webp' },
  breach_strike: { textureKey: 'card-art:breach_strike_anime', fileName: 'breach-strike-anime.webp' },
  sworn_edge: { textureKey: 'card-art:sworn_edge_anime', fileName: 'sworn-edge-anime.webp' },
  kindred_flame: { textureKey: 'card-art:kindred_flame_anime', fileName: 'kindred-flame-anime.webp' },
  communion_light: { textureKey: 'card-art:communion_light_anime', fileName: 'communion-light-anime.webp' },
  warband_cleave: { textureKey: 'card-art:warband_cleave_anime', fileName: 'warband-cleave-anime.webp' },
  phalanx_thrust: { textureKey: 'card-art:phalanx_thrust_anime', fileName: 'phalanx-thrust-anime.webp' },
  massed_volley: { textureKey: 'card-art:massed_volley_anime', fileName: 'massed-volley-anime.webp' },
  pack_instinct: { textureKey: 'card-art:pack_instinct_anime', fileName: 'pack-instinct-anime.webp' },
  grove_lash: { textureKey: 'card-art:grove_lash_anime', fileName: 'grove-lash-anime.webp' },
  deepening_frost: { textureKey: 'card-art:deepening_frost_anime', fileName: 'deepening-frost-anime.webp' },
  gathering_storm: { textureKey: 'card-art:gathering_storm_anime', fileName: 'gathering-storm-anime.webp' },
  umbral_choir: { textureKey: 'card-art:umbral_choir_anime', fileName: 'umbral-choir-anime.webp' },
  kindling_rite: { textureKey: 'card-art:kindling_rite_anime', fileName: 'kindling-rite-anime.webp' },
  whetstone_vow: { textureKey: 'card-art:whetstone_vow_anime', fileName: 'whetstone-vow-anime.webp' },
  thunderhead: { textureKey: 'card-art:thunderhead_anime', fileName: 'thunderhead-anime.webp' },
  bulwark_of_the_line: { textureKey: 'card-art:bulwark_of_the_line_anime', fileName: 'bulwark-of-the-line-anime.webp' },
  riposte_guard: { textureKey: 'card-art:riposte_guard_anime', fileName: 'riposte-guard-anime.webp' },
  emberguard: { textureKey: 'card-art:emberguard_anime', fileName: 'emberguard-anime.webp' },
  wildfire_rite: { textureKey: 'card-art:wildfire_rite_anime', fileName: 'wildfire-rite-anime.webp' },
  hallowed_toll: { textureKey: 'card-art:hallowed_toll_anime', fileName: 'hallowed-toll-anime.webp' },
  grove_communion: { textureKey: 'card-art:grove_communion_anime', fileName: 'grove-communion-anime.webp' },
  rustbind_hex: { textureKey: 'card-art:rustbind_hex_anime', fileName: 'rustbind-hex-anime.webp' },
  blooded_fang: { textureKey: 'card-art:blooded_fang_anime', fileName: 'blooded-fang-anime.webp' },
  hoarfrost_creed: { textureKey: 'card-art:hoarfrost_creed_anime', fileName: 'hoarfrost-creed-anime.webp' },
  pikewall_oath: { textureKey: 'card-art:pikewall_oath_anime', fileName: 'pikewall-oath-anime.webp' },
  sanctified_vigil: { textureKey: 'card-art:sanctified_vigil_anime', fileName: 'sanctified-vigil-anime.webp' },
  oathplate: { textureKey: 'card-art:oathplate_anime', fileName: 'oathplate-anime.webp' },
  graveside_rite: { textureKey: 'card-art:graveside_rite_anime', fileName: 'graveside-rite-anime.webp' },
  enfilade_volley: { textureKey: 'card-art:enfilade_volley_anime', fileName: 'enfilade-volley-anime.webp' },
  rearguard_pike: { textureKey: 'card-art:rearguard_pike_anime', fileName: 'rearguard-pike-anime.webp' },
  gravelight_choir: { textureKey: 'card-art:gravelight_choir_anime', fileName: 'gravelight-choir-anime.webp' },
  rimebound_pact: { textureKey: 'card-art:rimebound_pact_anime', fileName: 'rimebound-pact-anime.webp' },
  stormrank_relay: { textureKey: 'card-art:stormrank_relay_anime', fileName: 'stormrank-relay-anime.webp' },
  packline_flank: { textureKey: 'card-art:packline_flank_anime', fileName: 'packline-flank-anime.webp' },
  cleaving_creed: { textureKey: 'card-art:cleaving_creed_anime', fileName: 'cleaving-creed-anime.webp' },
  bramble_covenant: { textureKey: 'card-art:bramble_covenant_anime', fileName: 'bramble-covenant-anime.webp' },
  marksmans_creed: { textureKey: 'card-art:marksmans_creed_anime', fileName: 'marksmans-creed-anime.webp' },
  rimebarb_vigil: { textureKey: 'card-art:rimebarb_vigil_anime', fileName: 'rimebarb-vigil-anime.webp' },
};
