import assert from 'node:assert/strict';
import { equipmentCatalog } from '../src/data/equipmentContent';
import { equipmentItemPinKey } from '../src/data/equipmentLootSources';
import { equipmentLootConfig, awardEquipment, encounterEquipmentPool, equipmentDropPercent, preferredEventEquipmentPool, eventEquipmentPool } from '../src/run/equipmentLoot';
import { createRun } from '../src/run/runState';
import { readEquipmentTracking, setEquipmentTracking, EQUIPMENT_TRACKING_KEY, type TrackingStorage } from '../src/meta/equipmentTracking';
import { equipmentChanceText, trackedEncounterLoot, trackedEventLoot } from '../src/game/ui/equipmentLootTrackingModel';
const ref = { itemId: 'duelist_knot', itemVersion: 1, setVersion: 1 };
const solo = encounterEquipmentPool(['bandit_duelist']);
assert.equal(equipmentDropPercent(solo, equipmentLootConfig.fightChanceBps, ref), equipmentLootConfig.fightChanceBps / 100 / 6);
const weighted = [{ ...ref, weight: 3 }, { itemId: 'wind_charm', itemVersion: 1, weight: 1 }];
assert.equal(equipmentDropPercent(weighted, 2000, ref), 15);
assert.equal(equipmentDropPercent(weighted, 0, ref), 0);
assert.equal(equipmentDropPercent([], 10000, ref), 0);
assert.equal(equipmentDropPercent(weighted, 10000, { ...ref, itemVersion: 2 }), 0);
const ids = ['bandit_duelist', 'hunter'];
const pack = encounterEquipmentPool(ids);
for (const entry of pack) assert.equal(entry.weight, Math.max(...ids.map(id => encounterEquipmentPool([id]).find(row => equipmentItemPinKey(row) === equipmentItemPinKey(entry))?.weight ?? 0)));
assert.deepEqual(encounterEquipmentPool([...ids, ...ids]), pack);
assert.equal(eventEquipmentPool('equip_fencing_hall', 1, 'leave'), undefined);
const event = eventEquipmentPool('equip_fencing_hall', 1, 'take_piece')!;
const owned = [{ itemId: 'duelist_coat' }, { itemId: 'duelist_crest' }];
const preferred = preferredEventEquipmentPool(event.entries, owned);
assert.equal(equipmentDropPercent(preferred, event.chanceBps, ref), 100);
assert.equal(equipmentDropPercent(preferred, event.chanceBps, event.entries[0]!), 0);
assert.deepEqual(preferredEventEquipmentPool(event.entries, event.entries), event.entries);
const run = createRun(5);
for (let seed = 1; seed <= 30; seed++) {
  const state = { ...run, seed };
  const oldOwned = new Set(owned.map(item => item.itemId)), oldUnowned = event.entries.filter(entry => !oldOwned.has(entry.itemId));
  assert.deepEqual(awardEquipment(state, 'event', 'fixture', oldUnowned.length ? oldUnowned : event.entries, event.chanceBps),
    awardEquipment(state, 'event', 'fixture', preferred, event.chanceBps));
}
const values = new Map<string, string>();
const storage: TrackingStorage = { getItem: key => values.get(key) ?? null, setItem: (key, value) => { values.set(key, value); } };
setEquipmentTracking(ref, 'enemies', true, storage); setEquipmentTracking(ref, 'events', true, storage);
assert.equal(readEquipmentTracking(storage).length, 1);
assert.equal(trackedEncounterLoot(['bandit_duelist'], readEquipmentTracking(storage)).length, 1);
assert.equal(trackedEncounterLoot(['hunter'], [{ ...ref, itemVersion: 2, enemies: true, events: false }]).length, 0);
assert.equal(trackedEventLoot({ ...run, ownedEquipment: [{ ...ref, instanceId: 'owned' }] }, 'equip_fencing_hall', 1, readEquipmentTracking(storage))[0]!.percent, 0);
setEquipmentTracking(ref, 'enemies', false, storage);
assert.equal(trackedEncounterLoot(['bandit_duelist'], readEquipmentTracking(storage)).length, 0);
assert.equal(readEquipmentTracking(storage)[0]!.events, true);
setEquipmentTracking(ref, 'events', false, storage); assert.deepEqual(readEquipmentTracking(storage), []);
values.set(EQUIPMENT_TRACKING_KEY, '{bad'); assert.deepEqual(readEquipmentTracking(storage), []);
values.set(EQUIPMENT_TRACKING_KEY, JSON.stringify([{ ...ref, itemVersion: 999, enemies: true, events: true }])); assert.deepEqual(readEquipmentTracking(storage), []);
assert.deepEqual(readEquipmentTracking({ getItem: () => { throw Error(); }, setItem: () => { throw Error(); } }), []);
assert.equal(equipmentChanceText(0.00001), '<0.01%');
assert.equal(equipmentCatalog.item(ref.itemId, ref.itemVersion).name, 'Duelist Knot');
console.log('Equipment tracking audit: weighted odds, pack max-weight union, pinned refs, zero eligibility, event unowned/repeat ownership, 30 unchanged reward seeds, independent toggles, malformed/unavailable storage passed.');
